# Generated by Django 4.0.2 on 2022-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('date', models.DateField(verbose_name='日付')),
                ('in_time', models.TimeField(verbose_name='出勤')),
                ('out_time', models.TimeField(verbose_name='退勤')),
                ('rest_time', models.TimeField(verbose_name='休憩')),
                ('other', models.CharField(max_length=100, verbose_name='備考')),
            ],
        ),
    ]
