# Generated by Django 4.0.2 on 2022-05-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='other',
            field=models.CharField(max_length=1000, verbose_name='備考'),
        ),
    ]
