# Generated by Django 4.0.2 on 2022-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_works_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='other',
            field=models.CharField(max_length=1000, null=True, verbose_name='備考'),
        ),
    ]
