# Generated by Django 4.0.2 on 2022-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_works_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='other',
            field=models.CharField(default='', max_length=1000, verbose_name='備考'),
        ),
    ]
