# Generated by Django 4.0.2 on 2022-05-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_works_rest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='in_time',
            field=models.DurationField(verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='works',
            name='out_time',
            field=models.DurationField(verbose_name='退勤'),
        ),
        migrations.AlterField(
            model_name='works',
            name='rest_time',
            field=models.DateField(default='00:00', verbose_name='休憩'),
        ),
    ]
