# Generated by Django 4.0.2 on 2022-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_works_in_time_alter_works_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='in_time',
            field=models.TimeField(verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='works',
            name='out_time',
            field=models.TimeField(verbose_name='退勤'),
        ),
        migrations.AlterField(
            model_name='works',
            name='rest_time',
            field=models.TimeField(default='00:00', verbose_name='休憩'),
        ),
    ]
